# Generated by Django 3.2.19 on 2023-07-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='proxyCountryModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(default='', max_length=255)),
                ('local_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='proxyModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('address', models.CharField(default='', max_length=255)),
                ('protocol', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
